apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth-handler-8276
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/auth-handler-8276
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
